Vagrant.configure("2") do |config|

  # docker port fowarding
  # this allows you to access docker daemon running inside the VM,
  # from your host machine.
  # the host port is set to something random (4242) to avoid
  # trouble with existing docker daemons you might have on your host.
  config.vm.network "forwarded_port", guest: 2375, host: 4040

  # fix for "stdin: is not a tty" and "ttyname: inappropriate ioctl for device"
  # https://github.com/mitchellh/vagrant/issues/1673#issuecomment-28288042
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # if machine fails to boot don't wait too long.
  config.vm.boot_timeout = 60

  # synced folder
  config.vm.synced_folder "work", "/work", create: true,
    owner: "vagrant", group: "vagrant"

  # using geerling's box instead of canonical (which does not enable internet inside box)
  #config.vm.box = "geerlingguy/ubuntu1604"
  config.vm.box = "hashicorp/precise64"
  # set machine name in vagrant status
  config.vm.define "devops" do |devops|
  end
  config.vm.provider :virtualbox do |vb|
    # set the name of box in Virtualbox GUI
    vb.name = "devops"
  end

  # install puppet on machine
  # install puppet-modules
  # On Windows I have tried r10k as well as rcoleman-puppet_module
  # neither of these appear to work.

  config.vm.provision :shell, :path => "../scripts/install-puppet.sh"

  # provision with puppet
  config.vm.provision :puppet do |puppet|
    puppet.module_path = "environments/production/modules"
    puppet.manifests_path = "environments/production/manifests/"
    #puppet.options = "--verbose --debug"

  end

end
