Vagrant.configure("2") do |config|
  # fix for "stdin: is not a tty" and "ttyname: inappropriate ioctl for device"
  # https://github.com/mitchellh/vagrant/issues/1673#issuecomment-28288042
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # using geerling's box instead of canonical (which does not enable internet inside box)
  config.vm.box = "geerlingguy/ubuntu1604"
  # set machine name in vagrant status
  config.vm.define "devops" do |devops|
  end
  config.vm.provider :virtualbox do |vb|
    # set the name of box in Virtualbox GUI
    vb.name = "devops"
  end

  # install puppet on machine
  # install puppet-modules
  # On Windows I have tried r10k as well as rcoleman-puppet_module
  # neither of these appear to work.

  config.vm.provision :shell, :inline => <<-SHELL
    apt-get update -q
    apt-get install -y puppet
    puppet module install puppetlabs-stdlib
    puppet module install nvogel-ansible
    puppet module install garethr-docker
  SHELL

  # provision with puppet
  config.vm.provision :puppet do |puppet|
    puppet.manifests_path = "manifests"
    puppet.module_path = "modules"
    #puppet.options = "--verbose --debug"
  end

end
