Vagrant.configure("2") do |config|

  config.vm.network "private_network", ip: "84.84.87.95"
  config.vm.network "forwarded_port", guest: 8140, host: 8140
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"
  config.vm.boot_timeout = 60

  # create a synced folder `pwd`/work -> /work
  config.vm.synced_folder "#{ENV['HOMEDRIVE']}\\#{ENV['HOMEPATH']}\\work", "/work", create: true,
    owner: "vagrant", group: "vagrant"

  # set machine name in vagrant status
  machine_name = "vagrant-puppetmaster"
  config.vm.define machine_name do |puppetmaster|
  end
  config.vm.provider :virtualbox do |vb|
    # set the name of box in Virtualbox GUI
    vb.name = machine_name
    # allow access to internet
    # (esp machines listed in your etc hosts)
    # http://stackoverflow.com/a/18457420/682912
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    # increase allocated RAM so that docker containers
    # can run
    vb.customize ["modifyvm", :id,"--memory", "3072"]
  end

  # Generic Box.
  # config.vm.box = "generic/ubuntu1604"
  config.vm.box = "kmm/ubuntu-xenial64"

end
