Vagrant.configure("2") do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.network "private_network", ip: "84.84.87.89"
  config.vm.network "forwarded_port", guest: 9095, host: 9095
  config.vm.hostname = "docker-jenkins"
  # set machine name in vagrant status
  config.vm.define "docker-jenkins"

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.name = "docker-jenkins"
  end

  # fix for "stdin: is not a tty" and "ttyname: inappropriate ioctl for device"
  # https://github.com/mitchellh/vagrant/issues/1673#issuecomment-28288042
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  config.vm.provision :shell,
    inline: "sudo mkdir -p /opt/jenkins_home && sudo chmod 777 /opt/jenkins_home"

  config.vm.provision "docker" do |docker|
    docker.run "savishy/docker-jenkins:1.3",
      restart: "always",
      daemonize: true,
      auto_assign_name: false,
      args: "--name jenkins -v '/opt/jenkins_home:/var/lib/jenkins' -p '9095:8081' -p '50000:50000'"
  end


end
