Vagrant.configure("2") do |config|
  config.vm.box = "mwrock/Windows2016"
  machine_name = "windowsserver2016"
  config.vm.define machine_name

  config.vm.provider :hyperv do |hv|
    hv.vmname = machine_name
    hv.cpus = 1
    hv.memory =  2048
    hv.enable_virtualization_extensions = true
    hv.ip_address_timeout = 240
    hv.vm_integration_services = {
      guest_service_interface: true,
      heartbeat: true,
      key_value_pair_exchange: true,
      shutdown: true,
      time_synchronization: true,
      vss: true
    }

  config.vm.provision :shell do |s|
    s.path = "scripts/installChocolatey.ps1"
    s.args = ["Y","Y"]
    s.privileged = true
    s.powershell_args = "-executionpolicy unrestricted"
  end

  config.vm.provision :shell do |s|
    s.path = "scripts/chocoInstallDocker.ps1"
    s.args = ["Y","Y"]
    s.privileged = true
    s.powershell_args = "-executionpolicy unrestricted"
  end

  end

end
