# box for trying out docker for windows
# https://app.vagrantup.com/senglin/boxes/win-10-enterprise-vs2015community
Vagrant.configure("2") do |config|
  config.vm.box = "senglin/win-10-enterprise-vs2015community"
  config.vm.box_version = "1.0.0"
end
