# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
  config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.network "forwarded_port", guest: 5000, host: 5000
  config.vm.network "forwarded_port", guest: 9090, host: 9090

  # use same network space as the "docker-host" virtual machine. (84.84.87.*)
  config.vm.network "private_network", ip: "84.84.87.88"
  config.vm.hostname = "docker-registry"

  # fix for "stdin: is not a tty" and "ttyname: inappropriate ioctl for device"
  # https://github.com/mitchellh/vagrant/issues/1673#issuecomment-28288042
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # if machine fails to boot don't wait too long.
  config.vm.boot_timeout = 60

  # set machine name in vagrant status
  config.vm.define "docker-registry"

  config.vm.provider "virtualbox" do |vb|
    # Customize the amount of memory on the VM:
    vb.memory = "1024"
    vb.name = "docker-registry"
  end
  # install docker, run registry container.
  config.vm.provision "docker" do |d|
    # start registry
    d.run "registry:2",
      restart: "always",
      daemonize: true,
      auto_assign_name: false,
      args: "-p '5000:5000' --name 'registry'"
    # start registry UI
    d.run "konradkleine/docker-registry-frontend:v2",
      daemonize: true,
      restart: "always",
      auto_assign_name: false,
      args: "-p 9090:80 --name 'registry-frontend' -e ENV_DOCKER_REGISTRY_HOST=84.84.87.88 -e ENV_DOCKER_REGISTRY_PORT=5000"
  end
end
