Vagrant.configure("2") do |config|
  config.vm.network "private_network", ip: "84.84.87.90"
  ["9095"].each do |port|
      config.vm.network "forwarded_port", guest: port, host: port
  end

  # fix for "stdin: is not a tty" and "ttyname: inappropriate ioctl for device"
  # https://github.com/mitchellh/vagrant/issues/1673#issuecomment-28288042
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # if machine fails to boot don't wait too long.
  config.vm.boot_timeout = 60

  # create a synced folder `pwd`/work -> /work
  config.vm.synced_folder "#{ENV['HOMEDRIVE']}\\#{ENV['HOMEPATH']}\\jenkins-home",
    "/var/lib/jenkins",
    create: true,
    owner: "vagrant",
    group: "vagrant"


  # set machine name in vagrant status
  config.vm.define "vagrant-jenkins"
  config.vm.hostname = "vagrant-jenkins"
  config.vm.provider :virtualbox do |vb|
    # set the name of box in Virtualbox GUI
    vb.name = "vagrant-jenkins"
    # allow access to internet
    # (esp machines listed in your etc hosts)
    # http://stackoverflow.com/a/18457420/682912
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    # increase allocated RAM so that docker containers
    # can run
    vb.customize ["modifyvm", :id,"--memory", "2048"]
  end

  # Docker-Ready Box.
  #config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.box = "bento/ubuntu-16.04"
  # install puppet before provisioning with puppet (agentless mode)
  config.vm.provision :shell, :path => "../scripts/install-puppet.sh"

  # provision with puppet
  config.vm.provision :puppet do |puppet|
    puppet.module_path = "environments/production/modules"
    puppet.manifests_path = "environments/production/manifests/"
    #puppet.options = "--verbose --debug"
  end

  puts "-----------------------------"
  puts "JENKINS VAGRANT BOX"
  puts "Mount Point: #{ENV['HOMEDRIVE']}\\#{ENV['HOMEPATH']}\\jenkins-home"
  puts "This dir is the Jenkins Home Dir."
  puts "-----------------------------"

end
