Vagrant.configure("2") do |config|

  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.hostmanager.manage_guest = true
  config.hostmanager.ignore_private_ip = false

  ["4244","9095"].each do |port|
      config.vm.network "forwarded_port", guest: port, host: port
  end
  # Docker-Ready Box.
  #config.vm.box = "phusion/ubuntu-14.04-amd64"
  config.vm.box = "kmm/ubuntu-xenial64"

  # set machine name in vagrant status
  machine_name = "vagrant-jenkins"
  config.vm.define machine_name
  config.vm.hostname = machine_name
  config.vm.provider :virtualbox do |vb|
    # set the name of box in Virtualbox GUI
    vb.name = machine_name
    # allow access to internet
    # (esp machines listed in your etc hosts)
    # http://stackoverflow.com/a/18457420/682912
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    # increase allocated RAM so that docker containers
    # can run
    vb.customize ["modifyvm", :id,"--memory", "2048"]
  end

   config.vm.provider :hyperv do |hv|
     hv.vmname = machine_name
     hv.cpus = 1
     hv.memory =  2048
     hv.enable_virtualization_extensions = true
     hv.ip_address_timeout = 240
     hv.vm_integration_services = {
       guest_service_interface: true,
       heartbeat: true,
       key_value_pair_exchange: true,
       shutdown: true,
       time_synchronization: true,
       vss: true
     }
   end

  # install puppet before provisioning with puppet (agentless mode)
  config.vm.provision :shell, :path => "../scripts/install-puppet.sh"


  # provision with puppet
  config.vm.provision :puppet do |puppet|
    puppet.module_path = "environments/production/modules"
    puppet.manifests_path = "environments/production/manifests/"
    #puppet.options = "--verbose --debug"
  end

  puts "-----------------------------"
  puts "JENKINS VAGRANT BOX"
  puts "Mount Point: #{ENV['HOMEDRIVE']}\\#{ENV['HOMEPATH']}\\jenkins-home"
  puts "This dir is the Jenkins Home Dir."
  puts "-----------------------------"

end
