Vagrant.configure(2) do |config|
    config.vm.box = "bento/ubuntu-14.04"
    config.vm.network "forwarded_port", host: 8084, guest: 8084
    config.vm.network "forwarded_port", host: 9000, guest: 9000
    config.vm.network "forwarded_port", host: 9001, guest: 9001

    config.vm.provider "virtualbox" do |vb|
        vb.name = "spinnaker"
        vb.memory = "3072"
    end
    
    config.vm.provision :shell,
    inline: "sudo apt-get install -qqy python"

    config.vm.provision :ansible do |ansible|
        ansible.verbose = "vvvv"
        ansible.playbook = "provisioning/ansible/playbook.yml"
        ansible.galaxy_role_file = "provisioning/ansible/requirements.yml"
        ansible.galaxy_roles_path = "provisioning/ansible/"
    end


end