Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # docker port fowarding
  # this allows you to access docker daemon running inside the VM,
  # from your host machine.
  # the host port is set to something random (4243) to avoid
  # trouble with existing docker daemons you might have on your host.

  # 4243: docker
  # 4440: rundeck
  # 3306: mysql server
  # 8080: http application
  # 8081: http application
  # 9000: sonarqube
  # 5556,7001: weblogic
  config.vm.network "private_network", ip: "84.84.87.87"
  ["4243","4440","3306","5556","7001","8080","8081","8082","9000"].each do |port|
      config.vm.network "forwarded_port", guest: port, host: port
  end

  # fix for "stdin: is not a tty" and "ttyname: inappropriate ioctl for device"
  # https://github.com/mitchellh/vagrant/issues/1673#issuecomment-28288042
  config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

  # if machine fails to boot don't wait too long.
  config.vm.boot_timeout = 60

  # create a synced folder `pwd`/work -> /work
  config.vm.synced_folder "#{ENV['HOMEDRIVE']}\\#{ENV['HOMEPATH']}\\work", "/work", create: true,
    owner: "vagrant", group: "vagrant"

  config.vm.synced_folder "#{ENV['HOMEDRIVE']}\\#{ENV['HOMEPATH']}\\workspace", "/workspace", create: true,
    owner: "vagrant", group: "vagrant"

  # set machine name in vagrant status
  config.vm.define "docker-ansible-host" do |devops|
  end
  config.vm.provider :virtualbox do |vb|
    # set the name of box in Virtualbox GUI
    vb.name = "docker-ansible-host"
    # allow access to internet
    # (esp machines listed in your etc hosts)
    # http://stackoverflow.com/a/18457420/682912
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

    # increase allocated RAM so that docker containers
    # can run 
    vb.customize ["modifyvm", :id,"--memory", "2048"]
  end

  # Docker-Ready Box.
  config.vm.box = "phusion/ubuntu-14.04-amd64"

  # install puppet before provisioning with puppet (agentless mode)
  config.vm.provision :shell, :path => "../scripts/install-puppet.sh"

  # provision with puppet
  config.vm.provision :puppet do |puppet|
    puppet.module_path = "environments/production/modules"
    puppet.manifests_path = "environments/production/manifests/"
    #puppet.options = "--verbose --debug"
    puppet.hiera_config_path = "hiera/hiera.yaml"
  end

  puts "-----------------------------"
  puts "Mount Point: #{ENV['HOMEDRIVE']}\\#{ENV['HOMEPATH']}\\work"
  puts "Use this folder to share work between your host machine and the VM."
  puts "Forwarded Ports: "
  puts "- 4243: This port exposes the Docker Remote API to your host.
  You can hit http://localhost:4243 with API requests and
  Docker API running inside the VM will execute these requests."
  puts "-----------------------------"

end
