# Load Vagrantfile.setup#
# ref: https://github.com/erran-r7/multiple_vagrantfiles
load File.expand_path('../Vagrantfile.setup', __FILE__)

Vagrant.configure(2) do |config|
  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  # setup each machine.
  config.vm.define "samba-share" do |config2|

    # custom config block for AWS provider.
    config2.vm.provider :aws do |ec2, override|
      ec2.keypair_name = $keypair_name
      ec2.access_key_id = $access_key_id
      ec2.secret_access_key = $secret_access_key
      ec2.security_groups = $security_groups
      override.ssh.private_key_path = $private_key_path
      ec2.region = "ap-south-1"
      ec2.availability_zone = "ap-south-1a"
      ec2.ami = "ami-c2ee9dad" #canonical ubuntu 16.04 server
      ec2.instance_type = "t2.micro"
      override.ssh.username = "ubuntu"
      ec2.tags = {
        'Name'         => $ec2_instance
      }
      ec2.block_device_mapping = [
        {
            'DeviceName' => "/dev/sda1",
            'VirtualName' => "samba-share-data",
            'Ebs.VolumeSize' => 32,
            'Ebs.DeleteOnTermination' => true,
            'Ebs.VolumeType' => 'gp2',
        }
      ]
      override.vm.synced_folder ".", "/vagrant", disabled: true

    end
  end

  ###################
  # PROVISIONING
  ###################

  # Ensure Python installed for Ansible provision
  config.vm.provision :shell,
    inline: "sudo apt-get install -qqy python"

  config.vm.provision :ansible do |ansible|
    ansible.verbose = "vv"
    ansible.playbook = "provisioning/playbook.yml"
    ansible.galaxy_role_file = "provisioning/requirements.yml"
    ansible.galaxy_roles_path = "provisioning/"
  end

end
